name       : polkit-kde-agent
version    : 5.12.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/polkit-kde-agent-1-5.12.2.tar.xz : a936006df397637640e0a3c5ceb1ad70d9820917a51360640c8ee404355adc9c
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
