name       : polkit-kde-agent
version    : 5.24.4
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/polkit-kde-agent-1-5.24.4.tar.xz : 955246c593d0332bfbe386e81aaf7714e9ac8b8e7743c8c2e4f334b28dd685ad
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
