name       : polkit-kde-agent
version    : 5.13.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.0/polkit-kde-agent-1-5.13.0.tar.xz : 95dd1da6458f0777f494d18647e07776c77477a6887316738868a54f5f024b69
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
