name       : polkit-kde-agent
version    : 5.15.5
release    : 32
source     :
    - https://download.kde.org/stable/plasma/5.15.5/polkit-kde-agent-1-5.15.5.tar.xz : 628ce9a02defa31e98a6a373abb6a1f2bf39f065eaf82fdbb4f93bf07165e267
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
