name       : polkit-kde-agent
version    : 5.16.1
release    : 34
source     :
    - https://download.kde.org/stable/plasma/5.16.1/polkit-kde-agent-1-5.16.1.tar.xz : 423a34ae90566e13fa3fb40f85f3f941fcd9d81157183ab113cadf79e164aa32
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
