name       : polkit-kde-agent
version    : 5.25.3
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/polkit-kde-agent-1-5.25.3.tar.xz : 95dd7433f42a6afbd01e03783fb36d4fc55ec7d8d7b1ab4146637e83f43d0648
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
