name       : polkit-kde-agent
version    : 5.18.5
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/polkit-kde-agent-1-5.18.5.tar.xz : 5e1733cb51c826c6215da4fbbc9c9568240275cf86b9922cd7a643d192a75a91
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
