name       : polkit-kde-agent
version    : 5.19.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/polkit-kde-agent-1-5.19.2.tar.xz : 9df44683fc1815f24e4f1d5bdf36d325880edb382593a144625c489d9cc6ba47
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
