name       : polkit-kde-agent
version    : 5.27.4
release    : 85
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/polkit-kde-agent-1-5.27.4.tar.xz : 6df939a1fe2ab3cc29a886d6037f9c39d21002940f35120a27e1e003568ca1e8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
